### DISCUSSION TITLE
Scrolling tag bundle list for Quick Reblog/Quick Tags

### DISCUSSION THREAD

**Discussion by Pandasaurus-Rex** [AprilSylph/XKit-Rewritten#232] [Suggestion Box]
It'd be helpful/more efficient if the QR box was a set height with a scrollable tag bundle list, because, right now, if you have a lot of tag bundles you end up with this super long list that stretches up (or down depending on if your QR box is above or below) the page. 

Edit: also, if you're trying to use tag bundles on a post at the very top of your dash and your list is long enough it goes off the page completely so you can't switch blogs and/or click the bundles at the top of the list.

**Comment by hellersqueen** [comment]
I have the exact opposite problem, as in the set height is too short and even though I have a short list of bundles, I still have to scroll super far to get to the one bundle I want. How can I make it expand?

**Reply by AprilSylph** [reply]
You could use a userstyle manager like Stylus and modify the element's `max-height` that way.

For no scrolling at all:
```css
#quick-reblog .quick-tags:not([hidden]) { max-height: none; }
```
Or, set how many buttons appear at once by modifying the last number here (I've set it to 8 rather than the default 4):
```css
#quick-reblog .quick-tags:not([hidden]) { max-height: calc(var(--button-height) * 8); }
```
