### ISSUE TITLE
Hide Post 'Reactions'

### ISSUE THREAD

**Issue by Imogine** [AprilSylph/XKit-Rewritten#1045]
### Concept

The concept would be a new 'Tweaks' to hide the new 'React' option on posts as well as hide the reactions placed on the post by other users.

**Comment by AprilSylph** [comment]
Post reactions would be gone by the time the update was approved. It's an April Fool's joke.

**Comment by marcustyphoon** [comment]
temporary user style for [stylus](<https://github.com/openstyles/stylus#releases>):

most browsers:
```css
.Y9XIm, .sfGru:has(> .Yw8w6) {
  display: none;
}
```
firefox compatible:
```css
.Y9XIm, .Yw8w6 {
  display: none;
}
```
