### ISSUE TITLE
Tweak Proposal: Remove notes bubble

### ISSUE THREAD

**Issue by marciebeans** [AprilSylph/XKit-Rewritten#1133]
### Concept

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/99446459/98206182-eea8-4184-8d6c-1ee0f1059a70)
This is purely an aesthetics issue, but I would love more than anything an option to get rid of the little bubble around the note count. thanks 4 all you guys do <3

**Comment by marcustyphoon** [comment]
In the off chance you aren't a Firefox user, here's a quick and dirty user style! (Unfortunately, Firefox is missing a styling engine feature that makes these kinds of things easier to write for user CSS extensions like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne).).

```css
article footer div:has(> span[title$=" notes"]) {
  border: none;
  padding: 0;
}

article footer span[title$=" notes"]  {
  font-weight: 700;
}

article footer span[title$=" notes"] > span  {
  color: unset;
}
```
