### ISSUE TITLE
Toggle to hide white ring around Instant Messaging icons (when minimized)

### ISSUE THREAD

**Issue by RobBoyBlunder** [AprilSylph/XKit-Rewritten#1187]
### Concept

tumblr's instant messaging seems to have gotten an update that is fine otherwise, but now the minimized icons in the corner have a huge glaring white ring around them that is quite painful on my eyes and distracting as a part of the UI.

I think it would be nice to have a toggle for the white ring, or maybe even the ability to just make it darker so it's not super bright/obvious maybe? I'm not sure how difficult that would be to implement, but I figured it was worth suggesting at the very least.

I didn't see this in the suggestions, I apologize if it had already been mentioned!

**Comment by Charlignon** [comment]
For the record, this colour has the same value as the post background, and it is set by the theme in use. For default/deep blue theme, the ring will appear white, but on other themes like dark mode it will be far more discreet.
I don't know if this will be integrated to xkit (i'm not an admin), but in the meantime @RobBoyBlunder , since it can be an accessibility issue, here are two workarounds :
- Change your theme to one where site background and posts background are a similar colour (dark theme, pure white...)
- Install an addon that let you set custom css for websites, and add the code below for `www.tumblr.com` (it will keep the ring white, but a much softer colour) : 
```css
    #base-container > div:nth-of-type(3) div[role="figure"] {
        background-color: rgba(var(--white), 0.3) !important;
    }
```

**Comment by marcustyphoon** [comment]
I try to avoid nth-of-type selectors, since they can stop working or do unexpected things based on subtle changes to the Tumblr front end DOM structure. How about `button[aria-label^="Conversation with"]` as the parent part of the descendent selector? Of course, that makes the style specific to English-language Tumblr.

**Comment by Charlignon** [comment]
Agreed ! My tumblr isn't in English so I avoided using this one. Does work though !
In the meantime I looked for a better selector, and looks like `button div[role="figure"]` does the trick. I tried to look thoroughly and it seems to consistently select only message bubbles, but there's no 100% guarantee. That would give you
```css
    button div[role="figure" {
        background-color: rgba(var(--white), 0.3) !important;
    }
```
