### ISSUE TITLE
Timeformat: Unexpected formatting on mobile

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1391]
### Platform

MacOS 14.2.1 arm64 /// iOS 17.2.1

### Browser

Chrome 121.0.6167.85 /// iOS Safari 

### Addon version

0.23.3

### Details

When the browser viewport is *very* narrow, Timeformat doesn't hide the ummodified timestamp in items in the reblog chain.

![Screenshot 2024-02-01 at 3 12 59 PM](https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/2a3e1b06-87b0-406a-a71c-a1094da21129)

This appears to be due to this rule, which has higher specificity than our rule that sets `font-size: 0`.

```css
@media (max-width: 540px) {
  .fAAi8 .SqGYs {
    font-family: var(--font-family);
    margin-top: 6px;
    font-size: .78125rem;
    font-weight: 400;
    line-height: .6rem
  }
}
```
