### ISSUE TITLE
AccessKit Disable Animations: Pause/play buttons on videos stuck

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#513]
### Platform

MacOS 10.14.6

### Browser

Edge 98.0.1108.62, Chrome 99.0.4844.51, Firefox Dev 98.0b9

### Addon version

Actually #463 438c412

### Details

With AccessKit's disable animations option on, clicking to pause/play a native video element causes the pause/play button (`overlayPoof`) to get stuck on the screen, as the animation to "poof" them away is disabled.

Noticed on: https://www.tumblr.com/blog/view/punk/677822446268792832

```css
.kEaLk .EfjkQ svg {
    -webkit-animation: CuYh8 1s ease;
    animation: CuYh8 1s ease
}

@-webkit-keyframes CuYh8 {
    0% {
        opacity: 1;
        transform: scale(1)
    }

    to {
        opacity: 0;
        transform: scale(3)
    }
}
```

(aside: hey, weird, clicking the dogear corner on a post goes to blog/view now. interesting.)
